# Traces Observer Service config
tracesObserver:
  enabled: true
  developmentMode: false
  name: amp-traces-observer
  replicaCount: 1
  image:
    repository: ghcr.io/wso2/amp-traces-observer
    tag: "v0.1.0-rc11"
    pullPolicy: IfNotPresent
  port: 9098
  opensearchUrl: https://opensearch.openchoreo-observability-plane.svc.cluster.local:9200
  resourceLimits:
    memory: 256Mi
    cpu: 500m
  resourceRequests:
    memory: 128Mi
    cpu: 250m
  service:
    type: LoadBalancer

opensearch:
  username: "admin"
  password: "ThisIsTheOpenSearchPassword1"
