{{- if .Values.tracesObserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tracesObserver.name }}
  namespace: {{ .Values.tracesObserver.namespace }}
  labels:
    app.kubernetes.io/name: traces-observer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.tracesObserver.service.type }}
  selector:
    app: traces-observer
  ports:
    - name: http
      port: {{ .Values.tracesObserver.port }}
      targetPort: {{ .Values.tracesObserver.port }}
{{- end }}
